#! /bin/sh
force=0

if test $# -eq 0; then
  :;
elif test $# -eq 1; then
  case $1 in
  --force) force=1;;
  --help|-h)
     cat <<EOT
usage: bootstrap [--force]
bootstraps GDBM package
EOT
     ;;
  *) echo >&2 "$0: unrecognized option"
     exit 1;;
  esac
else
  echo >&2 "$0: too many arguments"
  exit 1
fi

if ! test -f README-hacking && test $force -eq 0; then
  echo >&2 "$0: bootstrapping from a non-checked-out distribution is risky"
  exit 1
fi

test -d m4 || mkdir m4
autoreconf -f -i -s